### ISSUE TITLE
Library not working in Godbolt Compiler explorer

### ISSUE THREAD

**Issue by correaa** [eliaskosunen/scnlib#101]
I am not sure if you have added the library to Godbolt, but in case you did, it is not working. 
I don't seem to be able to use it in there:

https://godbolt.org/z/fdvaEWjdM

A simple include cannot find the header after including it in the "green" libraries button.

```cpp
#include <scn/scan.h>
```

```
<source>:7:10: fatal error: scn/scan.h: No such file or directory
    7 | #include <scn/scan.h>
      |          ^~~~~~~~~~~~
compilation terminated.
Compiler returned: 1
```

I tried other variations with the same result.

**Comment by correaa** [comment]
Nevermind, I found the magic combination:

```
#include <scn/scn.h>
```

https://godbolt.org/z/T6j36rdPn

**Comment by correaa** [comment]
Got it, the version in Godbolt is `v1`. Godbolt can work with a "nightly" master if configured to do so, BTW

**Comment by correaa** [comment]
Do you want me to add the master version to Godbolt?

**Comment by eliaskosunen** [comment]
Thank you for doing the necessary legwork over at CE! I haven't done any contributions there myself, so it's dependent on people like you. Having a trunk-version there doesn't sound like a bad idea, either.

Closing this issue as WONTFIX, as the progress is tracked over at CE.

**Comment by correaa** [comment]
No problem. 

To be conservative and not overstep I put the tag v2.0.0 in CE.

The CE PR is being processed still.

**Comment by correaa** [comment]
The infrastructure for CE is merged now.

https://github.com/compiler-explorer/compiler-explorer/pull/6121

But I think I partially screwed up.
I mistakenly thought that scn was a header-only library, so the test code compiles, but it doesn't link, so it cannot be run:

https://godbolt.org/z/sf8v5zo1q

I don't know how to make non-header-only libraries in Godbolt.

**Comment by correaa** [comment]
The people that put libscn in CE have this:

https://github.com/correaa/infra/blob/main/bin/yaml/libraries.yaml#L1850C1-L1865C19

```yaml
    scnlib:
      build_type: cmake
      extra_cmake_arg:
      - -DSCN_TESTS=OFF
      - -DSCN_EXAMPLES=OFF
      - -DSCN_BENCHMARKS=OFF
      - -DSCN_DOCS=OFF
      make_targets:
      - scn
      repo: eliaskosunen/scnlib
      target_prefix: refs/tags/v
      targets:
      - '0.4'
      - 1.1.2
      - 2.0.0
      type: github
```

I don't see immediately what can be wrong with it.
